<<<<<<< HEAD
version: '3.8'

services:
  # 1. Le Serveur API (Laravel)
  backend:
    build: ./backend
    container_name: laravel_api
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  # 2. Le Frontend (Angular)
  frontend:
    build: ./frontend
    container_name: angular_front
=======
services:
  # Le frontend Angular
  frontend:
    image: node:20
    working_dir: /app
>>>>>>> master
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
<<<<<<< HEAD
    stdin_open: true
    tty: true
    command: npm start


  # 3. La Base de Données (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: sqllabs
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  # 4. L'interface de gestion BDD
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_ui
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
=======
    command: sh -c "npx ng serve --host 0.0.0.0"
    depends_on:
      - backend
  # Le backend APIrest Laravel
  backend:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db-sqlabs
      - DB_PORT=3306
      - DB_DATABASE=sqlabs_db
      - DB_USERNAME=sqlabs_user
      - DB_PASSWORD=password_gate
    depends_on:
      - db-sqlabs

  # La base de données MySQL
  db-sqlabs:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: sqlabs_db
      MYSQL_USER: sqlabs_user
      MYSQL_PASSWORD: password_gate
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

  # INTERFACE DB (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db-sqlabs
    depends_on:
      - db-sqlabs

volumes:
  mysql_data:
>>>>>>> master
